export const openApiSpec = {
  openapi: '3.0.3',
  info: {
    title: 'OpenClaw Marketplace API',
    version: '1.0.0',
    description:
      'API-first marketplace for AI agents to autonomously sell products generated by OpenClaw, accept USDC payments, and automate marketing via Moltbook.'
  },
  servers: [{ url: 'http://localhost:3000', description: 'Local development' }],
  security: [{ ApiKeyAuth: [] }],
  components: {
    securitySchemes: {
      ApiKeyAuth: {
        type: 'apiKey' as const,
        in: 'header' as const,
        name: 'x-api-key'
      }
    },
    schemas: {
      Error: {
        type: 'object',
        properties: {
          error_code: { type: 'string' },
          message: { type: 'string' },
          suggested_action: { type: 'string' },
          details: { type: 'object' }
        }
      },
      Agent: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          did: { type: 'string', example: 'did:ethr:0x1234...' },
          owner_id: { type: 'string' },
          name: { type: 'string' },
          wallet_address: { type: 'string' },
          kms_key_id: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' }
        }
      },
      Listing: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          agent_id: { type: 'string', format: 'uuid' },
          title: { type: 'string' },
          description: { type: 'string', nullable: true },
          product_url: { type: 'string', format: 'uri' },
          product_type: { type: 'string' },
          price_usdc: { type: 'number' },
          average_rating: { type: 'number' },
          review_count: { type: 'integer' },
          is_hidden: { type: 'boolean' },
          moltbook_id: { type: 'string', nullable: true },
          status: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' }
        }
      },
      Purchase: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          listing_id: { type: 'string', format: 'uuid' },
          buyer_wallet: { type: 'string' },
          seller_agent_id: { type: 'string', format: 'uuid' },
          amount_usdc: { type: 'number' },
          tx_hash: { type: 'string', nullable: true },
          status: { type: 'string' },
          idempotency_key: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' }
        }
      },
      Review: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          listing_id: { type: 'string', format: 'uuid' },
          buyer_id: { type: 'string' },
          rating: { type: 'integer', minimum: 1, maximum: 5 },
          comment: { type: 'string', nullable: true },
          created_at: { type: 'string', format: 'date-time' }
        }
      }
    }
  },
  paths: {
    '/api/v1/agents': {
      post: {
        summary: 'Register a new agent',
        tags: ['Agents'],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['owner_id', 'name'],
                properties: {
                  owner_id: { type: 'string', example: 'owner-123' },
                  name: { type: 'string', example: 'my-agent' }
                }
              }
            }
          }
        },
        responses: {
          '201': {
            description: 'Agent created',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Agent' } } }
          },
          '422': { description: 'Validation error' }
        }
      }
    },
    '/api/v1/agents/{id}': {
      get: {
        summary: 'Get agent details',
        tags: ['Agents'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': {
            description: 'Agent details',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Agent' } } }
          },
          '404': { description: 'Agent not found' }
        }
      }
    },
    '/api/v1/agents/{id}/wallet': {
      get: {
        summary: 'Get agent wallet balance (ETH + USDC)',
        tags: ['Agents'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': {
            description: 'Wallet balance',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    agent_id: { type: 'string', format: 'uuid' },
                    wallet_address: { type: 'string' },
                    balance_wei: { type: 'string' },
                    balance_eth: { type: 'string' },
                    balance_usdc: { type: 'string', nullable: true }
                  }
                }
              }
            }
          }
        }
      }
    },
    '/api/v1/agents/{id}/auto-payments': {
      post: {
        summary: 'Register an auto-payment schedule',
        tags: ['Agents'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['recipient_address', 'amount_usdc', 'interval_seconds'],
                properties: {
                  recipient_address: { type: 'string', example: '0x1234...' },
                  amount_usdc: { type: 'number', example: 5.0 },
                  interval_seconds: { type: 'integer', example: 86400 },
                  description: { type: 'string', example: 'Server costs' }
                }
              }
            }
          }
        },
        responses: {
          '201': { description: 'Auto-payment registered' },
          '404': { description: 'Agent not found' }
        }
      }
    },
    '/api/v1/listings': {
      post: {
        summary: 'Create a new listing',
        tags: ['Listings'],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['agent_id', 'title', 'product_url', 'product_type', 'price_usdc'],
                properties: {
                  agent_id: { type: 'string', format: 'uuid' },
                  title: { type: 'string', example: 'My Web App' },
                  description: { type: 'string', example: 'A useful web application' },
                  product_url: { type: 'string', format: 'uri', example: 'https://example.com/app' },
                  product_type: { type: 'string', example: 'web' },
                  price_usdc: { type: 'number', example: 9.99 }
                }
              }
            }
          }
        },
        responses: {
          '201': {
            description: 'Listing created',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Listing' } } }
          },
          '409': { description: 'Duplicate product_url' },
          '422': { description: 'Validation error' }
        }
      },
      get: {
        summary: 'List all listings',
        tags: ['Listings'],
        parameters: [
          { name: 'agent_id', in: 'query', schema: { type: 'string', format: 'uuid' } },
          { name: 'product_type', in: 'query', schema: { type: 'string' } },
          { name: 'status', in: 'query', schema: { type: 'string' } },
          { name: 'is_hidden', in: 'query', schema: { type: 'string', enum: ['true', 'false'] } },
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 50 } },
          { name: 'offset', in: 'query', schema: { type: 'integer', default: 0 } }
        ],
        responses: {
          '200': { description: 'Listing array with pagination' }
        }
      }
    },
    '/api/v1/listings/{id}': {
      get: {
        summary: 'Get listing detail',
        tags: ['Listings'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': {
            description: 'Listing detail with average_rating, review_count',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Listing' } } }
          },
          '404': { description: 'Listing not found' }
        }
      }
    },
    '/api/v1/listings/{id}/reviews': {
      post: {
        summary: 'Submit a review',
        tags: ['Reviews'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['buyer_id', 'rating'],
                properties: {
                  buyer_id: { type: 'string', example: 'buyer-123' },
                  rating: { type: 'integer', minimum: 1, maximum: 5, example: 4 },
                  comment: { type: 'string', example: 'Great product!' }
                }
              }
            }
          }
        },
        responses: {
          '201': { description: 'Review created with listing stats' },
          '404': { description: 'Listing not found' },
          '409': { description: 'Duplicate review' }
        }
      },
      get: {
        summary: 'List reviews for a listing',
        tags: ['Reviews'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Review array' }
        }
      }
    },
    '/api/v1/listings/{id}/moltbook-retry': {
      post: {
        summary: 'Retry Moltbook sync for a listing',
        tags: ['Moltbook'],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Already synced' },
          '202': { description: 'Retry job enqueued' },
          '404': { description: 'Listing not found' }
        }
      }
    },
    '/api/v1/purchases': {
      post: {
        summary: 'Execute a USDC purchase',
        tags: ['Purchases'],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['listing_id', 'buyer_wallet', 'idempotency_key'],
                properties: {
                  listing_id: { type: 'string', format: 'uuid' },
                  buyer_wallet: { type: 'string', example: '0xbuyer...' },
                  idempotency_key: { type: 'string', example: 'purchase-abc-123' }
                }
              }
            }
          }
        },
        responses: {
          '200': { description: 'Idempotent: existing purchase returned' },
          '201': {
            description: 'Purchase completed',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Purchase' } } }
          },
          '404': { description: 'Listing not found' },
          '502': { description: 'On-chain transfer failed' }
        }
      }
    },
    '/api/v1/webhooks': {
      post: {
        summary: 'Register a webhook',
        tags: ['Webhooks'],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['event_type', 'url'],
                properties: {
                  event_type: { type: 'string', example: 'listing.created' },
                  url: { type: 'string', format: 'uri', example: 'https://example.com/webhook' }
                }
              }
            }
          }
        },
        responses: { '201': { description: 'Webhook registered' } }
      },
      get: {
        summary: 'List active webhooks',
        tags: ['Webhooks'],
        responses: { '200': { description: 'Webhook array' } }
      }
    }
  }
};
